run_name: ddpm_imagenet128_test_inference
seed: 42
data_dir: ./data/imagenet100_128x128/train
image_size: 128
batch_size: 16
num_workers: 8
num_classes: 100
num_epochs: 5
learning_rate: 2e-4
weight_decay: 1e-4

num_train_timesteps: 250
num_inference_steps: 250
num_inference_samples: 500
samples_per_class: 5
beta_start: 1e-4
beta_end: 1e-2
beta_schedule: linear

variance_type: fixed_small
prediction_type: epsilon

unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

use_ddim: False
use_cfg: False

# Optional (explicit):
clip_sample: True
clip_sample_range: 1.0
save_intermediate_steps: True
intermediate_save_interval: 50